### ISSUE TITLE
Upgrade Amazon EKS CNI to most recent version to stay in sync

### ISSUE THREAD

**Issue by JacobHeidelbachDFDS** [dfds/infrastructure-modules#6]
https://github.com/aws/amazon-vpc-cni-k8s/releases
https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html

**Comment by abstrask** [comment]
This was fixed (a while ago). Now we apply the AWS recommended version of VPC CNI automatically, based on the version of EKS deployed.
