### ISSUE TITLE
Traefik access log should not show requests returning HTTP 200

### ISSUE THREAD

**Issue by abstrask** [dfds/infrastructure-modules#61]
At least until we collect logs in a proper tool, we should filter out Traefik access logs to exclude 1xx and 2xx status codes.

This is done with the CLI argument `--accessLog.filters.statusCodes="300-399,400-499,500-599"`.

**Comment by wcarlsen** [comment]
@abstrask didn't you solve this?

**Comment by abstrask** [comment]
@wcarlsen Only in production - not in code - so it has probably been overwritten by now.

**Comment by wcarlsen** [comment]
@abstrask it is running on Hellman. I'm closing this issue.
