### ISSUE TITLE
Upgrade terraform to 1.4.x

### ISSUE THREAD

**Issue by jakob-nielsen-dfds** [dfds/infrastructure-modules#766]
As terraform 1.4.x has been released and the primary build agent image `ubuntu-latest` on Azure DevOps has been updated to this, it would be very useful if the modules would allow using terraform 1.4.x.

Either requiring 1.4.x or allowing both 1.3.x and 1.4.x, i.e.: required_version = "~> 1.4.0, ~>1.3.0", or allow for minor version updates.

[ubuntu-latest (22.04) specification](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md).

[Latest terraform release note](https://github.com/hashicorp/terraform/blob/v1.4.2/CHANGELOG.md).

**Comment by samidbb** [comment]
@jakob-nielsen-dfds are you able to test using this branch enable-minor-tf-version-upgrade?

**Comment by jakob-nielsen-dfds** [comment]
I can verify that referencing the feature branch `enable-minor-tf-version-upgrade` I was able to successfully run `terragrunt plan` using terraform 1.4.2 and terragrunt 0.45.

Using reference below:
```hcl
terraform {
  source = "git::https://github.com/dfds/infrastructure-modules.git//database/postgres?ref=enable-minor-tf-version-upgrade"
}
```

**Comment by samidbb** [comment]
merged linked PR
