### ISSUE TITLE
Suggestion: AWS EKS addons version map maybe not needed

### ISSUE THREAD

**Issue by wcarlsen** [dfds/infrastructure-modules#901]
The AWS provider supports a data source [eks_addon_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/eks_addon_version) which can fetch the most recent addons version compatible with the Kubernetes version given, hence no need for maintaining the maps here https://github.com/dfds/infrastructure-modules/blob/master/_sub/compute/eks-addons/dependencies.tf. I would probably still leave in the custom overwrite in case of a bad release on AWS's part.

**Comment by avnes** [comment]
Thanks @wcarlsen - I have now added an issue on our Ops board to look into this at some point.
